import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen w-full flex-col items-center">
        <main className="flex h-screen w-screen max-w-5xl flex-col items-center px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
